In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(
    r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\realistic_e_commerce_sales_data.csv"
)

In [ ]:
df.shape

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\realistic_e_commerce_sales_data.csv"
)

In [3]:
df.shape

(1000, 12)

In [4]:
df.isnull().sum()

Customer ID          0
Gender               0
Region              50
Age                100
Product Name         0
Category             0
Unit Price           0
Quantity             0
Total Price          0
Shipping Fee         0
Shipping Status     50
Order Date           0
dtype: int64

In [5]:
df.isnull().sum()

Customer ID          0
Gender               0
Region              50
Age                100
Product Name         0
Category             0
Unit Price           0
Quantity             0
Total Price          0
Shipping Fee         0
Shipping Status     50
Order Date           0
dtype: int64

In [6]:
text_columns = [
    "Customer ID",
    "Gender",
    "Region",
    "Product Name",
    "Category",
    "Shipping Status"
]

for col in text_columns:
    df[col] = df[col].str.strip()

In [7]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    errors="coerce"
)

In [8]:
df["Order Date"].isnull().sum()

np.int64(0)

In [9]:
df["Region"] = df["Region"].fillna("Unknown")

In [10]:
median_age = df["Age"].median()

median_age

np.float64(49.0)

In [11]:
df["Age"] = df["Age"].fillna(median_age)

In [12]:
df["Age"].isnull().sum()

np.int64(0)

In [13]:
df["Shipping Status"] = df["Shipping Status"].fillna("Unknown")

In [14]:
df["Shipping Status"].isnull().sum()

np.int64(0)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df = df.drop_duplicates()

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.isnull().sum()

Customer ID        0
Gender             0
Region             0
Age                0
Product Name       0
Category           0
Unit Price         0
Quantity           0
Total Price        0
Shipping Fee       0
Shipping Status    0
Order Date         0
dtype: int64

In [19]:
df.shape

(1000, 12)

In [20]:
df["Calculated Total"] = (
    df["Unit Price"] * df["Quantity"]
)

In [21]:
df["Difference"] = (
    df["Total Price"] - df["Calculated Total"]
)

In [22]:
df["Difference"].value_counts()

Difference
 0.000000       980
-214.608082       3
-1716.864654      2
-64.382424        2
-1609.560612      2
-965.736368       2
-32.191212        1
-107.304041       1
-2575.296981      1
-8047.803060      1
-1609.560612      1
-3219.121224      1
-160.956061       1
-643.824245       1
-6438.242448      1
Name: count, dtype: int64

In [23]:
df["Price Check"] = np.where(
    np.isclose(
        df["Total Price"],
        df["Calculated Total"]
    ),
    "Valid",
    "Review"
)

In [24]:
df["Price Check"].value_counts()

Price Check
Valid     980
Review     20
Name: count, dtype: int64

In [25]:
df[df["Price Check"] == "Review"]

,Customer ID,Gender,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date,Calculated Total,Difference,Price Check
26,CUST0264,Male,East,59.0,Smartphone,Electronics,1658.432327,2,1600,11.59,In Transit,2023-02-01,3316.864654,-1716.864654,Review
83,CUST0219,Male,Unknown,48.0,Mouse,Accessories,62.191212,2,60,7.40,Returned,2023-08-20,124.382424,-64.382424,Review
84,CUST0037,Male,West,51.0,Keyboard,Accessories,103.652020,4,200,11.41,Returned,2023-05-20,414.608082,-214.608082,Review
110,CUST0223,Female,Unknown,20.0,Mouse,Accessories,62.191212,2,60,15.12,In Transit,2023-05-26,124.382424,-64.382424,Review
194,CUST0269,Male,North,64.0,Monitor,Electronics,621.912123,5,1500,6.93,Delivered,2023-04-23,3109.560612,-1609.560612,Review
209,CUST0134,Male,North,49.0,Monitor,Electronics,621.912123,5,1500,7.22,Returned,2023-08-05,3109.560612,-1609.560612,Review
215,CUST0194,Female,West,61.0,Mouse,Accessories,62.191212,1,30,10.41,Returned,2023-01-28,62.191212,-32.191212,Review
226,CUST0264,Female,West,59.0,Keyboard,Accessories,103.652020,4,200,10.49,Delivered,2023-08-21,414.608082,-214.608082,Review
244,CUST0128,Female,North,52.0,Monitor,Electronics,621.912123,3,900,11.04,Delivered,2023-10-25,1865.736368,-965.736368,Review
339,CUST0219,Female,South,48.0,Headphones,Accessories,207.304041,1,100,9.55,Delivered,2023-01-23,207.304041,-107.304041,Review
374,CUST0178,Female,South,44.0,Smartphone,Electronics,1658.432327,3,2400,19.31,Delivered,2023-06-03,4975.296981,-2575.296981,Review
421,CUST0011,Female,West,54.0,Smartphone,Electronics,1658.432327,2,1600,15.80,In Transit,2023-04-06,3316.864654,-1716.864654,Review
511,CUST0047,Male,East,41.0,Headphones,Accessories,207.304041,2,200,9.15,Returned,2023-04-23,414.608082,-214.608082,Review
560,CUST0204,Male,West,54.0,Laptop,Electronics,3109.560612,5,7500,19.71,Returned,2023-04-18,15547.803060,-8047.803060,Review
702,CUST0064,Male,West,61.0,Laptop,Electronics,3109.560612,1,1500,18.37,In Transit,2023-09-01,3109.560612,-1609.560612,Review
756,CUST0138,Female,West,46.0,Laptop,Electronics,3109.560612,2,3000,6.44,Delivered,2023-12-08,6219.121224,-3219.121224,Review
846,CUST0150,Male,West,63.0,Mouse,Accessories,62.191212,5,150,10.81,Delivered,2023-07-01,310.956061,-160.956061,Review
877,CUST0238,Male,East,26.0,Monitor,Electronics,621.912123,2,600,7.02,In Transit,2024-01-03,1243.824245,-643.824245,Review
883,CUST0077,Female,North,49.0,Monitor,Electronics,621.912123,3,900,14.86,In Transit,2023-04-27,1865.736368,-965.736368,Review
967,CUST0131,Female,North,67.0,Laptop,Electronics,3109.560612,4,6000,18.27,Unknown,2023-08-26,12438.242448,-6438.242448,Review

In [26]:
df.loc[
    df["Price Check"] == "Review",
    [
        "Customer ID",
        "Product Name",
        "Unit Price",
        "Quantity",
        "Total Price",
        "Calculated Total",
        "Difference"
    ]
]

,Customer ID,Product Name,Unit Price,Quantity,Total Price,Calculated Total,Difference
26,CUST0264,Smartphone,1658.432327,2,1600,3316.864654,-1716.864654
83,CUST0219,Mouse,62.191212,2,60,124.382424,-64.382424
84,CUST0037,Keyboard,103.652020,4,200,414.608082,-214.608082
110,CUST0223,Mouse,62.191212,2,60,124.382424,-64.382424
194,CUST0269,Monitor,621.912123,5,1500,3109.560612,-1609.560612
209,CUST0134,Monitor,621.912123,5,1500,3109.560612,-1609.560612
215,CUST0194,Mouse,62.191212,1,30,62.191212,-32.191212
226,CUST0264,Keyboard,103.652020,4,200,414.608082,-214.608082
244,CUST0128,Monitor,621.912123,3,900,1865.736368,-965.736368
339,CUST0219,Headphones,207.304041,1,100,207.304041,-107.304041
374,CUST0178,Smartphone,1658.432327,3,2400,4975.296981,-2575.296981
421,CUST0011,Smartphone,1658.432327,2,1600,3316.864654,-1716.864654
511,CUST0047,Headphones,207.304041,2,200,414.608082,-214.608082
560,CUST0204,Laptop,3109.560612,5,7500,15547.803060,-8047.803060
702,CUST0064,Laptop,3109.560612,1,1500,3109.560612,-1609.560612
756,CUST0138,Laptop,3109.560612,2,3000,6219.121224,-3219.121224
846,CUST0150,Mouse,62.191212,5,150,310.956061,-160.956061
877,CUST0238,Monitor,621.912123,2,600,1243.824245,-643.824245
883,CUST0077,Monitor,621.912123,3,900,1865.736368,-965.736368
967,CUST0131,Laptop,3109.560612,4,6000,12438.242448,-6438.242448

In [27]:
price_error_percentage = (
    (df["Price Check"] == "Review").mean() * 100
)

price_error_percentage

np.float64(2.0)

In [28]:
df.drop(
    columns=["Calculated Total"],
    inplace=True
)

In [29]:
df[
    [
        "Age",
        "Unit Price",
        "Quantity",
        "Total Price",
        "Shipping Fee"
    ]
].describe()

               Age   Unit Price     Quantity  Total Price  Shipping Fee
count  1000.000000  1000.000000  1000.000000  1000.000000   1000.000000
mean     46.926000   457.703777     3.008000  1346.600000     12.416390
std      14.257061   537.231434     1.404246  1834.037877      4.412185
min      18.000000    30.000000     1.000000    30.000000      5.000000
25%      37.000000    50.000000     2.000000   200.000000      8.560000
50%      49.000000   200.000000     3.000000   600.000000     12.315000
75%      58.000000   800.000000     4.000000  1500.000000     16.075000
max      69.000000  3109.560612     5.000000  7500.000000     19.980000

In [30]:
print(
    "Negative Unit Price:",
    (df["Unit Price"] < 0).sum()
)

print(
    "Invalid Quantity:",
    (df["Quantity"] <= 0).sum()
)

print(
    "Negative Total Price:",
    (df["Total Price"] < 0).sum()
)

print(
    "Negative Shipping Fee:",
    (df["Shipping Fee"] < 0).sum()
)

Negative Unit Price: 0
Invalid Quantity: 0
Negative Total Price: 0
Negative Shipping Fee: 0

In [31]:
print("Minimum Age:", df["Age"].min())
print("Maximum Age:", df["Age"].max())

Minimum Age: 18.0
Maximum Age: 69.0

In [32]:
print(df["Gender"].unique())
print(df["Region"].unique())
print(df["Product Name"].unique())
print(df["Category"].unique())
print(df["Shipping Status"].unique())

<StringArray>
['Male', 'Female']
Length: 2, dtype: str
<StringArray>
['North', 'West', 'South', 'East', 'Unknown']
Length: 5, dtype: str
<StringArray>
[   'Monitor', 'Headphones',     'Laptop', 'Smartwatch',   'Keyboard',
      'Mouse', 'Smartphone']
Length: 7, dtype: str
<StringArray>
['Electronics', 'Accessories', 'Wearables']
Length: 3, dtype: str
<StringArray>
['Returned', 'In Transit', 'Delivered', 'Unknown']
Length: 4, dtype: str

In [33]:
df.isnull().sum()

Customer ID        0
Gender             0
Region             0
Age                0
Product Name       0
Category           0
Unit Price         0
Quantity           0
Total Price        0
Shipping Fee       0
Shipping Status    0
Order Date         0
Difference         0
Price Check        0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.shape

(1000, 14)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer ID      1000 non-null   str
 1   Gender           1000 non-null   str
 2   Region           1000 non-null   str
 3   Age              1000 non-null   float64
 4   Product Name     1000 non-null   str
 5   Category         1000 non-null   str
 6   Unit Price       1000 non-null   float64
 7   Quantity         1000 non-null   int64
 8   Total Price      1000 non-null   int64
 9   Shipping Fee     1000 non-null   float64
 10  Shipping Status  1000 non-null   str
 11  Order Date       1000 non-null   datetime64[us]
 12  Difference       1000 non-null   float64
 13  Price Check      1000 non-null   str
dtypes: datetime64[us](1), float64(4), int64(2), str(7)
memory usage: 109.5 KB

In [37]:
df["Year"] = df["Order Date"].dt.year

In [38]:
df["Month"] = df["Order Date"].dt.month

In [39]:
df["Month Name"] = df["Order Date"].dt.month_name()

In [40]:
df["Quarter"] = (
    "Q" + df["Order Date"].dt.quarter.astype(str)
)

In [41]:
df["Year Month"] = (
    df["Order Date"]
    .dt.to_period("M")
    .astype(str)
)

In [42]:
bins = [0, 25, 35, 45, 55, 100]

labels = [
    "18-25",
    "26-35",
    "36-45",
    "46-55",
    "56+"
]

df["Age Group"] = pd.cut(
    df["Age"],
    bins=bins,
    labels=labels
)

In [43]:
df["Age Group"].value_counts()

Age Group
56+      309
46-55    286
36-45    172
26-35    135
18-25     98
Name: count, dtype: int64

In [44]:
df["Delivered Flag"] = (
    df["Shipping Status"] == "Delivered"
).astype(int)

In [45]:
df["Returned Flag"] = (
    df["Shipping Status"] == "Returned"
).astype(int)

In [46]:
df["In Transit Flag"] = (
    df["Shipping Status"] == "In Transit"
).astype(int)

In [47]:
df[
    [
        "Shipping Status",
        "Delivered Flag",
        "Returned Flag",
        "In Transit Flag"
    ]
].head(10)

  Shipping Status  Delivered Flag  Returned Flag  In Transit Flag
0        Returned               0              1                0
1      In Transit               0              0                1
2        Returned               0              1                0
3       Delivered               1              0                0
4       Delivered               1              0                0
5      In Transit               0              0                1
6      In Transit               0              0                1
7        Returned               0              1                0
8        Returned               0              1                0
9       Delivered               1              0                0

In [48]:
df["Revenue"] = df["Total Price"]

In [49]:
df[
    ["Unit Price", "Quantity", "Total Price", "Revenue"]
].head()

   Unit Price  Quantity  Total Price  Revenue
0       300.0         5         1500     1500
1       100.0         2          200      200
2       300.0         1          300      300
3       100.0         5          500      500
4      1500.0         3         4500     4500

In [50]:
df["Order Value Segment"] = pd.cut(
    df["Revenue"],
    bins=[0, 500, 1000, 2500, float("inf")],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

In [51]:
df["Order Value Segment"].value_counts()

Order Value Segment
Low          490
Very High    185
Medium       181
High         144
Name: count, dtype: int64

In [52]:
df[
    [
        "Order Date",
        "Year",
        "Month",
        "Month Name",
        "Quarter",
        "Year Month",
        "Age",
        "Age Group",
        "Shipping Status",
        "Delivered Flag",
        "Returned Flag",
        "In Transit Flag",
        "Revenue",
        "Order Value Segment"
    ]
].head(10)

,Order Date,Year,Month,Month Name,Quarter,Year Month,Age,Age Group,Shipping Status,Delivered Flag,Returned Flag,In Transit Flag,Revenue,Order Value Segment
0,2023-12-08,2023,12,December,Q4,2023-12,49.0,46-55,Returned,0,1,0,1500,High
1,2023-04-09,2023,4,April,Q2,2023-04,22.0,18-25,In Transit,0,0,1,200,Low
2,2023-08-28,2023,8,August,Q3,2023-08,54.0,46-55,Returned,0,1,0,300,Low
3,2023-01-18,2023,1,January,Q1,2023-01,23.0,18-25,Delivered,1,0,0,500,Low
4,2023-01-19,2023,1,January,Q1,2023-01,49.0,46-55,Delivered,1,0,0,4500,Very High
5,2023-01-11,2023,1,January,Q1,2023-01,64.0,56+,In Transit,0,0,1,400,Low
6,2023-10-23,2023,10,October,Q4,2023-10,27.0,26-35,In Transit,0,0,1,200,Low
7,2023-06-15,2023,6,June,Q2,2023-06,18.0,18-25,Returned,0,1,0,100,Low
8,2023-02-25,2023,2,February,Q1,2023-02,22.0,18-25,Returned,0,1,0,30,Low
9,2023-04-23,2023,4,April,Q2,2023-04,29.0,26-35,Delivered,1,0,0,300,Low

In [53]:
df.shape

(1000, 25)

In [54]:
df.columns

Index(['Customer ID', 'Gender', 'Region', 'Age', 'Product Name', 'Category',
       'Unit Price', 'Quantity', 'Total Price', 'Shipping Fee',
       'Shipping Status', 'Order Date', 'Difference', 'Price Check', 'Year',
       'Month', 'Month Name', 'Quarter', 'Year Month', 'Age Group',
       'Delivered Flag', 'Returned Flag', 'In Transit Flag', 'Revenue',
       'Order Value Segment'],
      dtype='str')

In [55]:
df.isnull().sum()

Customer ID            0
Gender                 0
Region                 0
Age                    0
Product Name           0
Category               0
Unit Price             0
Quantity               0
Total Price            0
Shipping Fee           0
Shipping Status        0
Order Date             0
Difference             0
Price Check            0
Year                   0
Month                  0
Month Name             0
Quarter                0
Year Month             0
Age Group              0
Delivered Flag         0
Returned Flag          0
In Transit Flag        0
Revenue                0
Order Value Segment    0
dtype: int64

In [56]:
df.dtypes

Customer ID                       str
Gender                            str
Region                            str
Age                           float64
Product Name                      str
Category                          str
Unit Price                    float64
Quantity                        int64
Total Price                     int64
Shipping Fee                  float64
Shipping Status                   str
Order Date             datetime64[us]
Difference                    float64
Price Check                       str
Year                            int32
Month                           int32
Month Name                        str
Quarter                           str
Year Month                        str
Age Group                    category
Delivered Flag                  int64
Returned Flag                   int64
In Transit Flag                 int64
Revenue                         int64
Order Value Segment          category
dtype: object

In [57]:
df.to_csv(
    r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\Cleaned\ecommerce_sales_final.csv",
    index=False
)

OSError: Cannot save file into a non-existent directory: 'C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\Cleaned'

In [58]:
import os

os.path.exists(
    r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\Cleaned\ecommerce_sales_final.csv"
)

False

In [59]:
import os

cleaned_folder = r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\Cleaned"

os.makedirs(cleaned_folder, exist_ok=True)

In [60]:
os.path.exists(cleaned_folder)

True

In [61]:
df.to_csv(
    r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\Cleaned\ecommerce_sales_final.csv",
    index=False
)

In [62]:
os.path.exists(
    r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\Cleaned\ecommerce_sales_final.csv"
)

True

In [63]:
import os

cleaned_folder = r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\Cleaned"

os.makedirs(cleaned_folder, exist_ok=True)

In [64]:
os.path.exists(cleaned_folder)

True

In [65]:
df.to_csv(
    r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\Cleaned\ecommerce_sales_final.csv",
    index=False
)

In [66]:
os.path.exists(
    r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\Cleaned\ecommerce_sales_final.csv"
)

True